name: Get Price Action

on:
  schedule:
    - cron: "52 * * * *"

jobs:
  getPrice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npm run fetch-price
