name: Get Price Action

on:
  schedule:
    - cron: "45 * * * *"

jobs:
  getPrice:
    runs-on: ubuntu-latest
    steps:
      - name: Get Price
        run: |
          curl https://chp.mananjoshi.me/api/get-price | jq
        shell: bash
